### ISSUE TITLE
Scale MSD to add connectivity for DynamoDB and validations.

### ISSUE THREAD

**Issue by GoswamiSH** [FINRAOS/MegaSparkDiff#52]
This issue is to add functionalities for data validation for DynamoDB.

**Comment by GoswamiSH** [comment]
@mmlinford From the discussion with @aosama and @matthewgillett  on the approach and extent of enhancements, I don't think we need any other feature as a pre-requisite to complete this issue. 

Will look into audienceproject/spark-dynamodb and get back to you. Let's discuss this with @matthewgillett  and @aosama as well.

**Comment by matthewgillett** [comment]
@GoswamiSH Please see the pull request #55 for DynamoDB support (as well as JSON format files). I used the https://github.com/awslabs/emr-dynamodb-connector dependency for reading the data from DynamoDB into Spark.
